name: ReportPollutionCI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: "Login"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      - name: "Generate .env"
        run: echo 'PORT=3000' >> backend/.env && echo 'PATH_HTML=../frontend/index.html' >> backend/.env &&  echo 'PATH_FRONTEND=../frontend' >> backend/.env
      - name: "DockerBuild"
        run: docker build -t hamacarina98/azrs:latest .
      - name: "DockerPush"
        run: docker push hamacarina98/azrs:latest
